export const CLEAR_BENCHMARKS = 'CLEAR_BENCHMARKS';
export const BENCHMARKS_RECEIVED = 'BENCHMARKS_RECEIVED';

export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const PROJECT_SELECTED = 'PROJECT_SELECTED';

export const VIEW_TIMING_CHANGED = 'VIEW_TIMING_CHANGED';
export const VIEW_BENCHMARKS_CHANGED = 'VIEW_BENCHMARKS_CHANGED';
export const VIEW_METRICS_CHANGED = 'VIEW_METRICS_CHANGED';
export const VIEW_ZOOM_CHANGED = 'VIEW_ZOOM_CHANGED';
export const VIEW_RESET ='VIEW_RESET';