export interface BestCliOptions {
    [key: string]: any,
    cache: boolean,
    cacheDirectory: string,
    useHttp: boolean,
    openPages: boolean,
    moduleDirectories: string[],
    moduleFileExtensions: string[],
    moduleNameMapper: {[moduleName:string]: string },
    modulePathIgnorePatterns: string[],
    runner: string,
    runnerConfig: any,
    benchmarkEnvironment: string,
    benchmarkMaxDuration: number,
    benchmarkMinIterations: number,
    benchmarkOnClient: boolean,
    benchmarkIterations: number,
    benchmarkOutput: string,
    benchmarkEnvironmentOptions: {[key:string]: string },
    testMatch: string[],
    samplesQuantileThreshold: number,
    normalize: boolean,
    outputMetricNames: string,
    outputTotals: boolean,
    outputHistograms: boolean,
    outputHistogramNames: string,
    histogramQuantileRange: [number, number],
    histogramMaxWidth: number,
    rootDir?: string
}
